language: node_js
node_js:
  - '0.12'
addons:
  sauce_connect:
    username: ernestos_barbosa
    access_key: access
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm run test
